### PR TITLE
Move C++ wrapper for playback

### LINKED ISSUE #491: [Request] Move playback C++ wrapper to include/k4arecord
**Is your feature request related to a problem? Please describe.**
The include/k4arecord directory doesn't contain C++ wrapper.
However, C++ wrapper for playback already exists in tools/k4aviewer/playback.hpp.
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/tools/k4aviewer/playback.hpp

**Describe the solution you'd like**
**Describe alternatives you've considered**
Move <code>playback.hpp</code> to include/k4arecord from tools/k4aviewer.

**Additional context**
If it is possible, I want to use record feature with wrapper like playback wrapper. (future work?)

### PR DESCRIPTION
**Pull request by UnaNancyOwen**
This pull request will move <code>playback.hpp</code> to <code>include/k4arecord</code>.
It is provides C++ wrapper for playback to developer.

## Fixes #491
Close #491

### Description of the changes:
- Move <code>playback.hpp</code> to <code>include/k4arecord</code>.
- Fix <code>src/record/sdk/CMakeLists.txt</code> to install <code>playback.hpp</code>.
- Fix include header of k4aviewer.

### Before submitting a Pull Request:
- [x] I reviewed [CONTRIBUTING.md](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/CONTRIBUTING.md)
- [x] I [built my changes](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md) locally
- [ ] I ran the [unit tests](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/testing.md)
- [ ] I ran the [functional tests](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/testing.md) with a device
- [ ] I ran the [performance tests](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/testing.md) with a device

### I tested changes on: 
- [x] Windows
- [ ] Linux

### CODE REVIEW

**Comment by williampMSFT** [comment]
@xthexder is added to the review. #Closed

**Comment by williampMSFT** [comment]
The main reason that this wasn't added to the public API originally is that it was developed while the k4a_playback_set_color_conversion API was being worked on, and we weren't quite sure yet what that API would look like yet.  We didn't want to promote it to the public API until we were sure it would match the C API.

Now that that's landed, I'm hesitant to promote this to the public API without matching the C API, which means we'd need to add an analogue to k4a_playback_set_color_conversion.

Other than that, this seems reasonable to me - @xthexder, any objections?

**Comment by wes-b** [comment]
We also comment on the issue #491 to address.

**Comment by UnaNancyOwen** [comment]
>I'm hesitant to promote this to the public API without matching the C API, which means we'd need to add an analogue to k4a_playback_set_color_conversion.

@williampMSFT Is this OK?
```cpp
/** Set the image format that color captures will be converted to.
 * By default the conversion format will be the same as the image format stored in the recording file, and no conversion will occur.
 * Throws error on failure.
 *
 * \sa k4a_playback_set_color_conversion
 */
void set_color_conversion(k4a_image_format_t format)
{
    k4a_result_t result = k4a_playback_set_color_conversion(m_handle, format);

    if (K4A_RESULT_SUCCEEDED != result)
    {
        throw error("Failed to set color conversion!");
    }
}
```

**Comment by williampMSFT** [comment]
> > I'm hesitant to promote this to the public API without matching the C API, which means we'd need to add an analogue to k4a_playback_set_color_conversion.
> 
> @williampMSFT Is this OK?
> 
> ```c++
> /** Set the image format that color captures will be converted to.
>  * By default the conversion format will be the same as the image format stored in the recording file, and no conversion will occur.
>  * Throws error on failure.
>  *
>  * \sa k4a_playback_set_color_conversion
>  */
> void set_color_conversion(k4a_image_format_t format)
> {
>     k4a_result_t result = k4a_playback_set_color_conversion(m_handle, format);
> 
>     if (K4A_RESULT_SUCCEEDED != result)
>     {
>         throw error("Failed to set color conversion!");
>     }
> }
> ```
Seems reasonable to me - per Wes and Brent's comments on the issue page #491, we're also going to have an internal review to make sure we're comfortable promoting this to the public API, so I'm going to hold off on hitting the actual 'approve' button until we've done that and made sure we aren't missing anything else, but I suspect the final change is going to look pretty close to what you have here.
Thanks!

**Comment by wes-b** [comment]
Changes look good, will sign off if there are no build issues

**Pull request merged**
