### PR TITLE
Allow more than 10 devices to be connected

### LINKED ISSUE #954: More than 10 devices
In the [depth_mcu.c](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/abccbce97ef6c086f02bf8b5a22af8f01e3e630d/src/depth_mcu/depth_mcu.c#L60), there's a hard-coded limit of the number devices to be 10.

> RETURN_VALUE_IF_ARG(K4A_RESULT_FAILED, device_index >= 10);

Can this be removed? I've tested 10 devices and it works fine. Now trying to have more.

Many thanks!

### PR DESCRIPTION
**Pull request by wes-b**
### Description of the changes:
- Increased the device index sanity check to 100

### CODE REVIEW

**Comment by wes-b** [comment]
@initialneil can you test this and confirm it works for you?

**Comment by initialneil** [comment]
@wes-b Thanks for the update.
It worked fine with 12 devices (1 master and 11 subordinates, 160us offset from one another), 30fps, 720p/1080p. Higher resolution of 1440p/1920p maxed out my pc's bandwidth, I need another capture card to test. I think it should be fine as well.

Tested with vs2015, Win10 x64. 

k4a-x12

**Comment by wes-b** [comment]
Awesome, thanks for the pic! Please remember after 10 devices the simple offset of 160us on the depth camera to avoid laser interference breaks down. See the comment in the linked issue to help address the issue.

**Comment by wes-b** [comment]
@initialneil curious of your PC setup spec's. I (and I know the community) would love to know what you are running to get that many Kinects successfully running simultaneously. I have seen 3 run at 30FPS with 1 USB host controller, but it wasn't rendering anything.

**Comment by initialneil** [comment]
@wes-b Thanks for asking. One key is to use 4 CPU memory cards, Quad Channel is critical for CPU bandwidth.
Another key is to use PCI-E USB3.0 capture cards. One K4A takes 5Gbps to work stably, so a PCI-E 2.0 4x card (20Gbps) can handle 4 K4A devices.
We're trying to build small holo capture studio with K4A. It would be great to receive interest/help from the community!

**Pull request merged**
