### PR TITLE
Update Doxygen output

### LINKED ISSUE #359: Host doxygen output on github pages
**Is your feature request related to a problem? Please describe.**
Doxygen output is not yet hosted.

**Describe the solution you'd like**
Modify doxygen output to fit style needs. We can then automatically generate static html output which can be hosted on GitHub.io by copying the static output to the gh-pages branch of this repo.

### PR DESCRIPTION
**Pull request by Brent-A**
### Description of the changes:
- Modified doxygen output
- Refactored public headers in to sections for doxygen
- Added stylesheets

### Before submitting a Pull Request:
- [X] I reviewed [CONTRIBUTING.md](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/CONTRIBUTING.md)
- [X] I [built my changes](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md) locally
- [X] I ran the [unit tests](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/testing.md)
- [ ] I ran the [functional tests](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/testing.md) with a device
- [ ] I ran the [performance tests](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/testing.md) with a device

### I tested changes on: 
- [X] Windows
- [ ] Linux

### CODE REVIEW

**Comment by Brent-A** [comment]
See http://brent-a.github.io/Azure-Kinect-Sensor-SDK for preview output

**Comment by xthexder** [comment]
I feel like we should have something on the main page / index. Maybe just a link back to the repository + the rest of the documentation?

**Comment by Brent-A** [comment]
This pull request just updates the output of the doxygen to be more readable. Once that's in we can host the output, and provide a link from the README.md

**Pull request merged**
