### PR TITLE
Performance improvement of Winforms' example

### PR DESCRIPTION
**Pull request by JorTurFer**
## Fixes #
#683
### Description of the changes:
- Change the way to generate the depth image from Bitmap.SetPixel to generate byte array and change it

### Before submitting a Pull Request:
- [x] I reviewed [CONTRIBUTING.md](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/CONTRIBUTING.md)
- [x] I [built my changes](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md) locally
- [x] I ran the [unit tests](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/testing.md)
- [x] I ran the [functional tests](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/testing.md) with a device
- [x] I ran the [performance tests](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/testing.md) with a device

### I tested changes on: 
- [x] Windows
- [ ] Linux

I tested the changes running the device localy:
image

### CODE REVIEW

**Comment by MsDerekMa** [comment]
@JorTurFer Thank you for the pull request. I took a look at it and it is indeed something we had planned to do, thanks for implementing it.
I had a couple comments. You should be able to reduce allocations and only allocate your Bitmap and backing buffer once. In addition, using the color object results in a bunch of function calls. So setting the bytes directly is a decent performance improvement. And then lastly I was seeing issues with the window updating the drawing.
Since there are a couple things, I am going to create a pull request into your branch that you can then review.

**Comment by MsDerekMa** [comment]
Apparently GitHub won't let me create a PR/suggestion for the file. So I just committed it.  Please let me know if these changes look good to you.

**Comment by JorTurFer** [comment]
Hi @MsDerekMa !
These changes feel great. From my side, all it's right with them.

**Pull request merged**
