### PR TITLE
k4a_device_start_cameras should use const k4a_device_configuration_t

### LINKED ISSUE #272: k4a_device_start_cameras should use const k4a_device_configuration_t
```k4a_result_t k4a_device_start_cameras(k4a_device_t device_handle, k4a_device_configuration_t *config)``` should be changed to ```k4a_result_t k4a_device_start_cameras(k4a_device_t device_handle, const k4a_device_configuration_t *config)```

### PR DESCRIPTION
**Pull request by rabbitdaxi**
### Description of the changes:
- k4a_device_start_cameras should use const k4a_device_configuration_t

### Before submitting a Pull Request:
- [x] I reviewed [CONTRIBUTING.md](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/CONTRIBUTING.md)
- [x] I [built my changes](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md) locally
- [x] I ran the [unit tests](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/testing.md)
- [x] I ran the [functional tests](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/testing.md) with a device
- [ ] I ran the [performance tests](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/testing.md) with a device

### I tested changes on: 
- [x] Windows
- [x] Linux

- Azure Kinetic Viewer Sanity check

### CODE REVIEW

**Comment by cdedmonds** [comment]
This is a compilation time breaking change. @wes-b @Brent-A how do we want to handle this?

**Comment by wes-b** [comment]
How so?

**Comment by rabbitdaxi** [comment]
Chatted offline

---
In reply to: [498448899](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/pull/393#issuecomment-498448899) [](ancestors = 498448899)

**Comment by rabbitdaxi** [comment]
Chatted offline, this should be fine, the current non-const structure pointer can implicitly cast to const pointer without issue (already have many examples having this).

---
In reply to: [498449547](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/pull/393#issuecomment-498449547) [](ancestors = 498449547)

**Pull request merged**
